export const pictures = [
  {
    url: '../../img/page-2/img-01.jpg',
    bannerUrl: '../../img/page-2/banner-01.jpg',
    alt: 'wet mountain valley',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-02.jpg',
    bannerUrl: '../../img/page-2/banner-02.jpg',
    alt: 'body of water surrounded by trees',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-03.jpg',
    bannerUrl: '../../img/page-2/banner-03.jpg',
    alt: 'landscape photography of mountains',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-04.jpg',
    bannerUrl: '../../img/page-2/banner-04.jpg',
    alt: 'brown wooden dock between lavender flower field',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-05.jpg',
    bannerUrl: '../../img/page-2/banner-05.jpg',
    alt: 'body of water surrounding with trees',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-06.jpg',
    bannerUrl: '../../img/page-2/banner-06.jpg',
    alt: 'forest heat by sunbeam',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-07.jpg',
    bannerUrl: '../../img/page-2/banner-07.jpg',
    alt: 'photo of valley',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-08.jpg',
    bannerUrl: '../../img/page-2/banner-08.jpg',
    alt: 'green grass field during sunset',
    width: 300,
    height: 150,
  },
  {
    url: '../../img/page-2/img-09.jpg',
    bannerUrl: '../../img/page-2/banner-09.jpg',
    alt: 'aerial shot of forest',
    width: 300,
    height: 150,
  },
];
